version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
      post-service:
        condition: service_started
      media-service:
        condition: service_started

  identity-service:
    build: ./identity-service
    container_name: identity-service
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./identity-service/.env
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  post-service:
    build: ./post-service
    container_name: post-service
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ./post-service/.env
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  media-service:
    build: ./media-service
    container_name: media-service
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ./media-service/.env
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
